cmake_minimum_required(VERSION 3.13)

set(SRC_FILES src/main.c src/MeshRotatorSystem.c)
if (USE_GL)
    set(SRC_FILES ${SRC_FILES} src/desktop_init.c)
    add_executable(${PROJECT_NAME} ${SRC_FILES})
elseif (NintendoDS)
    set(SRC_FILES ${SRC_FILES} src/ds_init.c src/NDSMaths.c)
    add_arm9_executable(${PROJECT_NAME} ${SRC_FILES})
    create_nds(${PROJECT_NAME} ${PROJECT_NAME})
    target_link_libraries(${PROJECT_NAME} nds-graphics)
endif()

set_property(TARGET ${PROJECT_NAME} PROPERTY C_STANDARD 99)
set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 14)
set(GCC_COVERAGE_COMPILE_FLAGS -Wall -Wextra -Werror -Wpedantic -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable)
target_compile_options(${PROJECT_NAME} PRIVATE ${GCC_COVERAGE_COMPILE_FLAGS})
target_link_libraries(${PROJECT_NAME} CodeStars-Engine)
get_target_property(INCLUDE_DIRS CodeStars-Engine INTERFACE_INCLUDE_DIRECTORIES)
target_include_directories(${PROJECT_NAME} PRIVATE ${INCLUDE_DIRS})