cmake_minimum_required(VERSION 3.20)
project(CodeStars LANGUAGES C)
option(OPTIMISATIONS_ENABLED "Optimisations for speed" OFF)
if(DEFINED OPTIMISATIONS_ENABLED)
    #add_compile_definitions(FIXMATH_NO_HARD_DIVISION)
    message(STATUS "FixMath Optimisations are enabled for this build")
endif()
add_compile_definitions(ecs_ftime_t=int)
add_subdirectory(Engine)
add_subdirectory(Game)
install(TARGETS ${CMAKE_PROJECT_NAME})
install(FILES $<TARGET_RUNTIME_DLLS:${CMAKE_PROJECT_NAME}> TYPE BIN)