cmake_minimum_required(VERSION 3.13)
project(CodeStars-Engine)
add_library(CodeStars-Engine INTERFACE)
file(GLOB platforms "cmake/platforms/*")
foreach(platform ${platforms})
    include(${platform})
endforeach(platform ${platforms})
add_subdirectory(libs)
get_target_property(INCLUDE_DIRS ${PROJECT_NAME}_libs INTERFACE_INCLUDE_DIRECTORIES)
target_include_directories(CodeStars-Engine INTERFACE ${INCLUDE_DIRS})
add_subdirectory(core)
add_subdirectory(platform-specifics)