set(WONDERFUL_TOOLCHAIN $ENV{WONDERFUL_TOOLCHAIN})
if (WONDERFUL_TOOLCHAIN STREQUAL "")
message(FATAL_ERROR "The WONDERFUL_TOOLCHAIN environment variable must be set!")
endif()
set(hint ${WONDERFUL_TOOLCHAIN}/toolchain/gcc-arm-none-eabi/bin)
find_program(CMAKE_ASM_COMPILER arm-none-eabi-gcc HINTS ${hint})
find_program(CMAKE_C_COMPILER arm-none-eabi-gcc HINTS ${hint})
find_program(CMAKE_CXX_COMPILER arm-none-eabi-g++ HINTS ${hint})
find_program(CMAKE_LINKER arm-none-eabi-ld HINTS ${hint})
find_program(CMAKE_AR arm-none-eabi-ar HINTS ${hint})
find_program(CMAKE_RANLIB arm-none-eabi-gcc-ranlib HINTS ${hint})
find_program(CMAKE_STRIP arm-none-eabi-strip HINTS ${hint})
set(WONDERFUL_INCLUDES ${WONDERFUL_TOOLCHAIN}/toolchain/gcc-arm-none-eabi/arm-none-eabi/include)
