set(WONDERFUL_TOOLCHAIN $ENV{WONDERFUL_TOOLCHAIN})
file(TO_CMAKE_PATH "$ENV{WONDERFUL_TOOLCHAIN}" WONDERFUL_TOOLCHAIN)
if (WONDERFUL_TOOLCHAIN STREQUAL "")
message(FATAL_ERROR "The WONDERFUL_TOOLCHAIN environment variable must be set!")
endif()
set(hint ${WONDERFUL_TOOLCHAIN}/toolchain/gcc-arm-none-eabi/bin)

find_program(ASM_COMPILER arm-none-eabi-gcc HINTS ${hint})
find_program(C_COMPILER arm-none-eabi-gcc HINTS ${hint})
find_program(CXX_COMPILER arm-none-eabi-g++ HINTS ${hint})
find_program(LINKER arm-none-eabi-ld HINTS ${hint})
find_program(AR arm-none-eabi-ar HINTS ${hint})
find_program(RANLIB arm-none-eabi-gcc-ranlib HINTS ${hint})
find_program(STRIP arm-none-eabi-strip HINTS ${hint})
set(CMAKE_ASM_COMPILER ${ASM_COMPILER} CACHE STRING "ASM Compiler" FORCE)
set(CMAKE_C_COMPILER ${C_COMPILER} CACHE STRING "C Compiler" FORCE)
set(CMAKE_CXX_COMPILER ${CXX_COMPILER} CACHE STRING "CXX Compiler" FORCE)
set(CMAKE_LINKER ${LINKER} CACHE STRING "Linker" FORCE)
set(CMAKE_AR ${AR} CACHE STRING "AR" FORCE)
set(CMAKE_STRIP ${STRIP} CACHE STRING "Strip" FORCE)
set(CMAKE_C_COMPILER_WORKS 1 CACHE STRING "c works" FORCE)
set(CMAKE_CXX_COMPILER_WORKS 1 CACHE STRING "cpp works" FORCE)
set(WONDERFUL_INCLUDES ${WONDERFUL_TOOLCHAIN}/toolchain/gcc-arm-none-eabi/arm-none-eabi/include)
set(WONDERFUL_LIBRARIES ${WONDERFUL_TOOLCHAIN}/gcc-arm-none-eabi/arm-none-eabi/lib)
