add_library(${PROJECT_NAME}_core INTERFACE)
add_subdirectory(memory)
add_subdirectory(maths)
add_subdirectory(graphics)
add_subdirectory(scene)
add_subdirectory(components)
target_link_libraries(${PROJECT_NAME}_core INTERFACE ${PROJECT_NAME}_libs )
target_link_libraries(${PROJECT_NAME} INTERFACE ${PROJECT_NAME}_core)